export const FETCH_WEATHER_DATA = "FETCH_WEATHER_DATA"
export const FETCH_WEATHER_DATA_SUCCESSFUL = "FETCH_WEATHER_DATA_SUCCESSFUL"
export const FETCH_WEATHER_DATA_FAILED = "FETCH_WEATHER_DATA_FAILED"

export const CONVERT_TEMPERATURE = "CONVERT_TEMPERATURE"
